version: '3'

services:
  app:
    container_name: gp-app
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    container_name: gp-db
    image: postgres:16.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
